import type { Technician, WorkOrder, Project, ProjectDocument, TimesheetLog, ServiceRequest } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImageUrl = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const technicians: Technician[] = [
  {
    id: 'tech-001',
    name: 'Alex Johnson',
    role: 'Lead Field Technician',
    email: 'alex.j@aaromach.com',
    phone: '555-111-2222',
    currentLocation: 'New York, NY',
    reliabilityScore: 95,
    currentWorkload: 3,
    skills: ['HVAC', 'Plumbing', 'Electrical', 'Cabling'],
    avatarUrl: getImageUrl('technician-1'),
  },
  {
    id: 'tech-002',
    name: 'Maria Garcia',
    role: 'Appliance Specialist',
    email: 'maria.g@aaromach.com',
    phone: '555-222-3333',
    currentLocation: 'Brooklyn, NY',
    reliabilityScore: 98,
    currentWorkload: 2,
    skills: ['Electrical', 'Appliance Repair', 'Refrigeration'],
    avatarUrl: getImageUrl('technician-2'),
  },
  {
    id: 'tech-003',
    name: 'David Smith',
    role: 'Senior Technician',
    email: 'david.s@aaromach.com',
    phone: '555-333-4444',
    currentLocation: 'Queens, NY',
    reliabilityScore: 88,
    currentWorkload: 5,
    skills: ['Plumbing', 'Carpentry', 'Welding'],
    avatarUrl: getImageUrl('technician-3'),
  },
  {
    id: 'tech-004',
    name: 'Sarah Chen',
    role: 'Smart Home Integrator',
    email: 'sarah.c@aaromach.com',
    phone: '555-444-5555',
    currentLocation: 'New York, NY',
    reliabilityScore: 92,
    currentWorkload: 1,
    skills: ['HVAC', 'Electrical', 'Smart Home', 'Networking'],
    avatarUrl: getImageUrl('technician-4'),
  },
   {
    id: 'tech-005',
    name: 'Ben Carter',
    role: 'Junior Technician',
    email: 'ben.c@aaromach.com',
    phone: '555-555-6666',
    currentLocation: 'Jersey City, NJ',
    reliabilityScore: 85,
    currentWorkload: 4,
    skills: ['Appliance Repair', 'Plumbing', 'Cabling'],
    avatarUrl: getImageUrl('technician-5'),
  },
];

export const workOrders: WorkOrder[] = [
  {
    id: 'wo-101',
    description: 'Fix leaking faucet in main bathroom',
    location: '123 Main St, New York, NY',
    requiredSkills: ['Plumbing'],
    priority: 'medium',
    status: 'assigned',
    assignedTechnicianId: 'tech-003',
    clientName: 'Residential Client',
    projectType: 'Maintenance',
    scheduleDate: '2024-07-20',
    scheduleTime: '11:00 AM EST',
    pay: 150.00,
  },
  {
    id: 'wo-102',
    description: 'Repair central AC unit not cooling',
    location: '456 Oak Ave, Brooklyn, NY',
    requiredSkills: ['HVAC', 'Electrical'],
    priority: 'high',
    status: 'in-progress',
    assignedTechnicianId: 'tech-001',
    clientName: 'Commercial Property',
    projectType: 'Repair',
    scheduleDate: '2024-07-18',
    scheduleTime: '2:00 PM EST',
    pay: 350.00,
  },
  {
    id: 'wo-103',
    description: 'Install new smart thermostat',
    location: '789 Pine Ln, New York, NY',
    requiredSkills: ['Electrical', 'Smart Home'],
    priority: 'low',
    status: 'unassigned',
    clientName: 'Smart Home Solutions',
    projectType: 'Installation',
    scheduleDate: '2024-07-25',
    scheduleTime: '10:00 AM EST',
    pay: 120.00,
  },
  {
    id: 'wo-104',
    description: 'Broken refrigerator compressor',
    location: '321 Elm St, Queens, NY',
    requiredSkills: ['Appliance Repair'],
    priority: 'critical',
    status: 'completed',
    assignedTechnicianId: 'tech-002',
    clientName: 'Restaurant Supply Co.',
    projectType: 'Emergency Repair',
    scheduleDate: '2024-07-15',
    scheduleTime: '4:00 PM EST',
    pay: 475.00,
  },
   {
    id: 'wo-105',
    description: 'Full electrical wiring inspection',
    location: '555 Market St, New York, NY',
    requiredSkills: ['Electrical'],
    priority: 'high',
    status: 'unassigned',
    clientName: 'Corporate Tower Mgmt',
    projectType: 'Inspection',
    scheduleDate: '2024-07-22',
    scheduleTime: '9:00 AM EST',
    pay: 600.00,
  },
   {
    id: 'wo-106',
    description: 'Water heater replacement',
    location: '888 Broadway, Brooklyn, NY',
    requiredSkills: ['Plumbing', 'HVAC'],
    priority: 'medium',
    status: 'in-progress',
    assignedTechnicianId: 'tech-001',
    clientName: 'Apartment Complex',
    projectType: 'Replacement',
    scheduleDate: '2024-07-19',
    scheduleTime: '1:00 PM EST',
    pay: 750.00,
  },
];

export const projects: Project[] = [
  {
    id: 'proj-001',
    name: 'Ki9 Refresh',
    client: 'Ki9',
    location: 'Detroit, MI',
    status: 'active',
    startDate: '2026-04-18',
    startTime: '9:00 AM EDT',
    estimatedDuration: '2 weeks',
    assignedTechnicianIds: ['tech-003'],
    team: [{ technicianId: 'tech-003', role: 'Project Lead' }, { technicianId: 'tech-001', role: 'Cabling Tech'}],
    scope: 'All PCs — full hardware refresh across site. Scope includes deinstallation of old equipment, packing for shipment, and installation of new desktops, monitors, and peripherals at all workstations.',
    onsiteContact: 'John Doe - 555-123-4567',
    siteAccessInstructions: 'Check in at front desk, badge required. Parking in Lot B. All personnel must wear safety vests while on the warehouse floor. Entry code for server room is 4821.',
    siteHazardNotes: [
      { id: 'h1', text: 'Forklift On-Site', type: 'danger'},
      { id: 'h2', text: 'Active Warehouse', type: 'info'},
    ],
    projectBudget: 15000,
    estimatedHours: 80,
    actualBudget: 7500,
    actualHours: 42,
    phases: [
      {
        id: 'phase-1',
        phaseNumber: 1,
        name: 'Deinstallation',
        notes: 'All de-installed equipment must be audited against the asset list before moving to packing.',
        tasks: [
          { id: 't1-1', name: 'Remove existing cabling', isCompleted: true, requiresPhoto: true },
        ],
      },
      {
        id: 'phase-2',
        phaseNumber: 2,
        name: 'Packing of Old Equipment',
        notes: 'Use provided packaging materials only. All boxes must be labeled with the Ki9 standard return label format.',
        tasks: [
          { id: 't2-1', name: 'Box items', isCompleted: true, requiresPhoto: false },
          { id: 't2-2', name: 'Add return labels', isCompleted: false, requiresPhoto: false },
          { id: 't2-3', name: 'Take pictures of packed items', isCompleted: false, requiresPhoto: true },
        ],
      },
    ],
  },
];

export const projectDocuments: ProjectDocument[] = [
  { id: 'doc-1', name: 'Site_Floor_Plan_Detroit.pdf', type: 'pdf', label: 'Site Doc', uploader: 'System Admin', uploadDate: 'Apr 18, 2026', size: '2.4 MB' },
  { id: 'doc-2', name: 'Existing_Setup_Reference.jpg', type: 'img', label: 'Contract', uploader: 'Corey Williams', uploadDate: 'Apr 18, 2026', size: '1.1 MB', url: getImageUrl('site-photo-1') },
  { id: 'doc-3', name: 'Client_Hardware_Spec.docx', type: 'doc', label: 'Contract', uploader: 'System Admin', uploadDate: 'Apr 17, 2026', size: '340 KB' },
  { 
    id: 'doc-4', 
    name: 'Deinstallation_Signoff.pdf', 
    type: 'pdf', 
    label: 'Sign-off', 
    uploader: 'David Smith', 
    uploadDate: 'Apr 19, 2026', 
    size: '800 KB',
    phaseId: 'phase-1',
  },
  {
    id: 'doc-5',
    name: 'cabling_removed.jpg',
    type: 'img',
    label: 'Photo',
    uploader: 'David Smith',
    uploadDate: 'Apr 19, 2026',
    size: '1.8 MB',
    phaseId: 'phase-1',
    taskId: 't1-1',
    url: getImageUrl('site-photo-2'),
  }
];

export const timesheetLogs: TimesheetLog[] = [
  {
    assignmentId: 'ts-1',
    projectId: 'proj-001',
    technicianId: 'tech-003', // David Smith
    date: 'Saturday, April 18, 2026',
    checkInTime: '8:04 AM',
    checkOutTime: '12:31 PM',
    totalHours: '4h 27m',
    totalMinutes: 267,
    logSummary: 'Deinstalled existing network switches in server room. Began boxing units for return shipment. Floor plan confirmed — forklift was active in loading dock area as noted.',
    completedTasks: ['Box items'],
    inProgressTasks: ['Remove existing cabling'],
    photos: [getImageUrl('site-photo-1'), getImageUrl('site-photo-2')],
  },
   {
    assignmentId: 'ts-2',
    projectId: 'proj-001',
    technicianId: 'tech-001', // Alex Johnson
    date: 'Saturday, April 18, 2026',
    checkInTime: '8:01 AM',
    checkOutTime: '5:05 PM',
    totalHours: '9h 04m',
    totalMinutes: 544,
    logSummary: 'Assisted with deinstallation and started running new CAT6A cabling for the refresh. All old patch panels have been removed. Coordinated with David on server room access.',
    completedTasks: ['Remove existing cabling'],
    inProgressTasks: ['Run new cabling'],
    photos: [],
  },
  {
    assignmentId: 'ts-3',
    projectId: 'proj-001',
    technicianId: 'tech-003', // David Smith
    date: 'Sunday, April 19, 2026',
    checkInTime: '8:30 AM',
    checkOutTime: '4:45 PM',
    totalHours: '8h 15m',
    totalMinutes: 495,
    logSummary: 'Finished boxing all old equipment and added return labels. All pallets are staged for pickup. Completed photo documentation of packed items.',
    completedTasks: ['Add return labels', 'Take pictures of packed items'],
    inProgressTasks: [],
    photos: [getImageUrl('site-photo-1')],
  }
];

export const serviceRequests: ServiceRequest[] = [
    { id: 'req-001', clientName: 'Global Corp', location: 'New York, NY', requestType: 'New Install', description: 'Office-wide network cabling installation.', status: 'new', submittedDate: '2024-07-22' },
    { id: 'req-002', clientName: 'Jane Doe', location: 'Brooklyn, NY', requestType: 'Repair', description: 'Security camera system is offline.', status: 'quoted', submittedDate: '2024-07-21' },
    { id: 'req-003', clientName: 'Quantum Industries', location: 'Jersey City, NJ', requestType: 'Inspection', description: 'Annual fire alarm system inspection.', status: 'scheduled', submittedDate: '2024-07-20' },
    { id: 'req-004', clientName: 'Burger Palace', location: 'Queens, NY', requestType: 'Quote', description: 'Quote for new POS system installation.', status: 'new', submittedDate: '2024-07-22' },
    { id: 'req-005', clientName: 'Local Library', location: 'New York, NY', requestType: 'Repair', description: 'Public Wi-Fi access points are malfunctioning.', status: 'closed', submittedDate: '2024-07-19' },
];
